### ISSUE TITLE
Proof of work or proof of stake? Smart contracts?

### ISSUE THREAD

**Issue by LRonHubs** [tezos/tezos#10]
The white paper describes this as a smart-contract, proof-of-stake cryptocurrency with self-amending capabilities. So far, I can't quite tell how to 

1) deploy a simple smart contract
2) run a proof-of-stake node
3) self-amend a node's code based on voting.

The readme appears to describe this as a proof-of-work coin. What's the deal with that? 

The language.pdf doc is useful for describing the language and how to write a contract but it doesn't cover these issues?

**Comment by tezos** [comment]
Yes, all of these are implemented. We use a very limited amount of proof of work for certain things, like creating a node identity, but the consensus doesn't rely on it. For instance blocks have a small proof of work to make sure they take longer to create than to reject as invalid. This is made orders of magnitude less computationally heavy than Bitcoin.

**Comment by rickyk586** [comment]
What proof-of-work algorithm is used?

**Comment by LRonHubs** [comment]
How am I supposed to develop for tezos if you dont have  example smart contracts for me to learn from

**Comment by LRonHubs** [comment]
2 and 3 are also important. How can I audit the staking system without knowing where the POS code is located? How can I question or perhaps suggest improvements to the protocol if its hidden behind a docker VM?

**Comment by j0sh** [comment]
@LRonHubs All your questions could be answered with a browse of the source code. The code is quite well written.

Example scripts: https://github.com/tezos/tezos/tree/master/test/contracts (not to mention http://www.michelson-lang.com)

The alphanet (including docker scripts), as far as I can tell, is built from what's on github. The alphanet protocol implementation is here https://github.com/tezos/tezos/tree/master/src/proto/alpha which has most of the PoS code. There is also a Medium article describing the layout of the source tree.
