### ISSUE TITLE
Michelson doc

### ISSUE THREAD

**Issue by fab13n** [tezos/tezos#100]
according to `src/proto/alpha/docs/lamguage.md`:
* `timestamp` can only be added with `nat`, not `int`. Is it on purpose or a typo?
* not clear whether `COMPARE` also works on union/product types
* in the full grammar at the end:
    * `s/DIV/EDIV/`
    * `CHECK_*` should be removed, now that arithmetic overflows have been removed
    * there's a reference to some `CAST` operator?
    * no more `FLOOR` / `CEIL` since there are no floats

**Comment by fab13n** [comment]
Also, substraction between timestamps `(-) : timestamp -> timestamp -> int` would make sense.

**Comment by klakplok** [comment]
All that should be fixed now, thanks for the reports.
