### ISSUE TITLE
alphabet.sh client got stuck

### ISSUE THREAD

**Issue by qdwang** [tezos/tezos#103]
![tezos-issue](https://user-images.githubusercontent.com/403616/29807811-2a908a90-8cc8-11e7-88ba-57e1d1025e27.png)

Why the alphabet client command show nothing? It's just got stuck here.
No error is shown.

macOS 10.12.6

**Comment by qdwang** [comment]
due to the poor network.

**Comment by OCamlPro-Henry** [comment]
The `alphanet.sh` script checks for update at _each_ run. This might indeed be painful if you have a high-latency connection. Should it happen agin, you might define `export TEZOS_ALPHANET_DO_NOT_PULL=yes` before to run `alphanet.sh` in order to deactivate the auto-update mechanism.
