### ISSUE TITLE
spendable / delegetable flags in doc

### ISSUE THREAD

**Issue by fab13n** [tezos/tezos#106]
I haven't found in the doc their exact meaning.

* I guess `delegatable=false` will prevent from performing a `tezos-client set delegate XXX`; but if `CREATE_CONTRACT` sets a delegate and the flag to `false`, does it imake the contract invalid, make it unchangeable, prevent the contract's funds from staking?
*  will `spendable=false` prevent spending from the code, or from tezos-client? Presumably not from both?

**Comment by klakplok** [comment]
Non delegatable means the delegate cannot be changed in the future. The delegate is set in stone when the contract is created.
Non spendable means that the manager cannot spend the funds. Only the script can.
