### ISSUE TITLE
what to do if private key is compromised before tezos launch?

### ISSUE THREAD

**Issue by tivalensol** [tezos/tezos#110]
Hi,

I believe my Tezos key might be compromised but as tezos is yet to launch, what security features do you have in place to stop any thefts?

**Comment by pmetzger** [comment]
This isn't a help line for Tezos. It is the bug tracking system for the source code. You should get in touch with the foundation, not post to the bug tracker.

**Comment by pmetzger** [comment]
(There was an email address on the fundraising web page for questions and assistance.)
