### ISSUE TITLE
Serious storage bug with type list !!!

### ISSUE THREAD

**Issue by qdwang** [tezos/tezos#111]
![list-bug](https://user-images.githubusercontent.com/403616/30237721-7a043108-956a-11e7-9d9d-98c4ab06d54f.png)

Please fix it as soon as possible...

**Comment by aaronwinter** [comment]
I was able to reproduce this on my node: 

```
$ ./alphanet.sh client run program container:/tmp/program.tz on storage "(List 1 2 3 4 5)" and input Unit
storage
  (List 5 4 3 2 1)
output
  Unit
```

with `program.tz` being:

```
parameter unit;
storage (list nat);
return unit;
code { };
```

After a quick look, I believe this might come from the application function in the `fold_right_s` here: https://github.com/tezos/tezos/blob/master/src/proto/alpha/script_ir_translator.ml#L724

**Comment by MiloDavis** [comment]
This bug has been fixed since 0197828. The person running try-michelson.com has not updated their node to apply the fix. The change has also not been pushed to the alphanet via an update, but will be shortly.

**Comment by MiloDavis** [comment]
This was also reported in #69.

**Comment by aaronwinter** [comment]
Nice. Thanks
