### ISSUE TITLE
Missing irmin-fs dependency

### ISSUE THREAD

**Issue by fab13n** [tezos/tezos#112]
In master branch, commit e303669674afd50904d8576b15be654ff48cb038: a dependency on `irmin-fs` is missing from `src/tezos-deps.opam`.

**Comment by MiloDavis** [comment]
I've tried to reproduce the issue by creating a fresh Opam switch and installing the dependencies, but I don't get any build errors. Can you post the exact error you're getting as well as the output of `opam list`?

**Comment by fab13n** [comment]
I redid the same manipulation, erasing `~/.opam` first, and couldn't reproduce! From memory, the error was `Error: Unbound module Irmin_fs` in the build logs.

**Comment by klakplok** [comment]
Fixed by requiring `irmin-unix >= 1.3`.
A good practice is to provide the output of `opam list` at the time of error.

**Comment by fredcy** [comment]
I'm getting this same error when building the alphanet branch today. Applying the above patch allowed `make build-deps` to finish.
