### ISSUE TITLE
Cannot get an existing contract's details (error 404)

### ISSUE THREAD

**Issue by tzs1** [tezos/tezos#115]
Executing this command:

`./alphanet.sh client rpc call /blocks/BKmwaG39KARTti5S161siTaJSvQHpr9NMngHr2jrD9awptxgpU2/proto/operations with '{}'`

Will output the list of operations of the specific block. This is for example the operation onm6qxGKcTtfbrbYupeqhEF3XJTz9dbh8eekX9ZG3ARfUh1ccPe:

`{ "hash": "onm6qxGKcTtfbrbYupeqhEF3XJTz9dbh8eekX9ZG3ARfUh1ccPe",
          "net_id": "NetXnvFUGSeFg7D",
          "branch": "BKkATbnXkNqrnpxH7REGcMfsyQff6HttaqGyiCeiKzEoeMCyYat",
          "source": "TZ1iuCv2Hozy1F9umFT5LYMWC3DbxSuSmSau",
          "public_key":
            "edpkuXNFrnZnZjSNKPZu5QkxPCseZDQW7XE6xLuADrozNoiM6bDydG",
          "fee": 0.000000, "counter": 1.000000,
          "operations":
            [ { "kind": "transaction", "amount": 10000000.000000,
                "destination": "TZ1tSMy8f3NLZkyt1WFL37jgiWVLpeiikFup" } ],
          "signature":
            "edsigtzRoYimyovhLUmjBd73o87EfHHG8CkgYhHRQ1JkyRcfyRJAzi3vxCH3wkemzU6HUy816w4rbw2QZ8qtX4ivKQoaeGz2UMc" }`

Wanting to get the details of operation's source contract, I execute this other command:

`./alphanet.sh client rpc call /blocks/head/proto/context/contracts/TZ1iuCv2Hozy1F9umFT5LYMWC3DbxSuSmSau`

This is the output:

`Fatal error:
  RPC Request failed:
    Path: http://127.0.0.1:8732/blocks/head/proto/context/contracts/TZ1iuCv2Hozy1F9umFT5LYMWC3DbxSuSmSau
    HTTP status: 404 (Not Found)
Try -help for a list of options and commands.`

**Comment by xuqzab** [comment]
**Same problem here, created 3 accounts under my_identity, errors getting balance on all 3:** 
$ ./alphanet.sh client list known contracts
gandalf: TZ1kqdcJFYjgBDS5aRFUKw5MdDD4EQmysqvN
bilbo: TZ1aMvSgxxqs666iWhgt3V5uKPK7z6FWJ77G
frodo: TZ1hAjYq5CR7Skv545LfxuQdLrZYmsFZzqdV
my_account: TZ1dUtu3jhAhRxP17NyhDNyjqdM9gWefXXZ3
my_identity: tz1Tm1be9ozr6dfD7kaErqAoPZM2XdGryS5A
$ ./alphanet.sh client get balance for bilbo
Fatal error:
  RPC Request failed:
    Path: http://127.0.0.1:8732/blocks/prevalidation/proto/context/contracts/TZ1aMvSgxxqs666iWhgt3V5uKPK7z6FWJ77G/balance
    HTTP status: 404 (Not Found)
**However my_account which was created by the alphanet.sh script works**
$ ./alphanet.sh client get balance for my_account
99,999.95 ꜩ
**Have run into same problem on more than one machine on docker containers created yesterday and today 10/24/17 and 10/25/17.**

**Comment by OCamlPro-Henry** [comment]
When the balance of an account step below 1tz the account is deleted from the blockchain (1tz is current value in the alphanet, not decided yet what will be its value in the mainnet). So it is expected that an RPC to `/blocks/head/proto/context/contracts/TZ1iuCv2Hozy1F9umFT5LYMWC3DbxSuSmSau` fails at some point in the future even if it used to work.

You might still access "old" state of the contract by querrying the state of an older block:
`/blocks/BKmwaG39KARTti5S161siTaJSvQHpr9NMngHr2jrD9awptxgpU2/proto/context/contracts/TZ1iuCv2Hozy1F9umFT5LYMWC3DbxSuSmSau`

This issue will now be tracked here: https://gitlab.com/tezos/tezos/issues/54
