### ISSUE TITLE
Error in command line argument 3 (my_identity) - couldn't to read the secret key alias file

### ISSUE THREAD

**Issue by tzs1** [tezos/tezos#118]
`Launching the docker container...
Restoring the peer identity from '/home/tz/.tezos-alphanet/identity.json'...
Restoring the secret keys from '/home/tz/.tezos-alphanet/secret keys'...
Peer_id: idsRBNnJkK7DnMhuwzCmVUPyYwcjbZ. Proof of work is higher than 24.00.
Waiting for the node to synchronize with the network...
Current head: BM8Ft46UH6ZrDN (2017-09-27T10:34:48Z)
Bootstrapped.
Generating new manager key (known as 'my_identity')...
Fatal error:
  Error in command line argument 3 (my_identity)
  couldn't to read the secret key alias file
  Ezjsonm.Parse_error(870828711, "JSON.of_buffer expected JSON text (JSON value)")
Try `-help` for a list of options and commands.
`

**Comment by MiloDavis** [comment]
Can you provide the identity file?

**Comment by tzs1** [comment]
`{
  "public_key": "d2bf99e7474c9c4f399df2f0cb9e4e9fbb7bd9aa29dc5df0e8db2c7cc3d79c5c",
  "secret_key": "db80e0322f0b5b9d38548370b287ca1602805678e9b06344949488534138c27e",
  "proof_of_work_stamp": "ccb5163b0a53ba43f876a7ac1e75c9b123be9ff22edde84b"
}`

**Comment by tzs1** [comment]
There is no secret key file (but there was before!)

**Comment by klakplok** [comment]
As it is an error from the JSON parser, it means that the file was corrupted at some point.
Cannot say much more without the file.

**Comment by tzs1** [comment]
Got the same error again. The file is empty! After the node was restarted, before that it was working.
