### ISSUE TITLE
Michelson Mode for Emacs creates many tmp files and uses all space on device

### ISSUE THREAD

**Issue by katelynsills** [tezos/tezos#120]
Hi, I've been using the michelson mode in emacs on GalliumOS, and after awhile, I start getting a message "No space left on device" when I click on one of the opcodes. I found that my inode usage was at 100% (`df -i .`), and tracked it to files being created in the `/tmp` folder. It looks like every refresh of the stack generates about 4 new files, each being a copy of the contract file. So for instance, I was looking at Milo's new password contract, which I called `wrong.tz` and after clearing the `tmp` folder and clicking once on an opcode in the contract, files `wrong.tz636280B` and `wrong.tz63629gs` and so forth are created in `/tmp`.

**Comment by MiloDavis** [comment]
I only count two new files. I've shrunk the number of files created down to one and added code to delete it after the deferred command finishes. It should be merged shortly.

Thanks for reporting this.

**Comment by katelynsills** [comment]
Sorry, you're right, it's only two files per click. Thanks, Milo! It's really a great tool!
