### ISSUE TITLE
Can't build on Mac High Sierra, OpenSSL issue.

### ISSUE THREAD

**Issue by edubai** [tezos/tezos#123]
$ opam install ssl
The following actions will be performed:
  ∗  install   conf-openssl     1             [required by ssl]
  ∗  install   ssl              0.5.4 
  ↻  recompile conduit-lwt-unix 1.0.2         [uses ssl]
  ↻  recompile cohttp-lwt-unix  0.99.0        [uses conduit-lwt-unix]
  ↻  recompile git-unix         1.11.2        [uses conduit-lwt-unix]
  ↻  recompile irmin-unix       1.3.0         [uses git-unix]
===== ∗  2   ↻  4 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[cohttp-lwt-unix] Archive in cache
[conduit-lwt-unix] Archive in cache
[git-unix] Archive in cache
[irmin-unix] Archive in cache
[ssl] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
⊘  removed   irmin-unix.1.3.0
⊘  removed   git-unix.1.11.2
⊘  removed   cohttp-lwt-unix.0.99.0
⊘  removed   conduit-lwt-unix.1.0.2
[ERROR] The compilation of conf-openssl failed at "pkg-config openssl".

#=== ERROR while installing conf-openssl.1 ====================================#
# opam-version 1.2.2
# os           darwin
# command      pkg-config openssl
# path         /Users/edubai/.opam/tezos/build/conf-openssl.1
# compiler     4.04.2
# exit-code    1
# env-file     /Users/edubai/.opam/tezos/build/conf-openssl.1/conf-openssl-66582-05296d.env
# stdout-file  /Users/edubai/.opam/tezos/build/conf-openssl.1/conf-openssl-66582-05296d.out
# stderr-file  /Users/edubai/.opam/tezos/build/conf-openssl.1/conf-openssl-66582-05296d.err

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions were aborted
  ∗  install cohttp-lwt-unix  0.99.0
  ∗  install conduit-lwt-unix 1.0.2 
  ∗  install git-unix         1.11.2
  ∗  install irmin-unix       1.3.0 
  ∗  install ssl              0.5.4 
The following actions failed
  ∗  install conf-openssl 1
The following changes have been performed
  ⊘  remove cohttp-lwt-unix  0.99.0
  ⊘  remove conduit-lwt-unix 1.0.2 
  ⊘  remove git-unix         1.11.2
  ⊘  remove irmin-unix       1.3.0 

=-=- conf-openssl.1 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
=> This package relies on external (system) dependencies that may be missing. `opam depext conf-openssl.1' may help you find the correct installation for your system.

The former state can be restored with:
    opam switch import "~/.opam/tezos/backup/state-20170904041921.export"
Mohameds-Mac-mini:tezos user$ make build-deps
+ true
+ opam pin --yes add --no-action --dev-repo sodium
[NOTE] Package sodium is already git-pinned to https://github.com/dsheets/ocaml-sodium.git.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[sodium] https://github.com/dsheets/ocaml-sodium.git updated
[sodium] Installing new package description from https://github.com/dsheets/ocaml-sodium.git

+ opam pin --yes add --no-action --dev-repo ocp-ocamlres
[NOTE] Package ocp-ocamlres is already git-pinned to git://github.com/OCamlPro/ocp-ocamlres.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[ocp-ocamlres] git://github.com/OCamlPro/ocp-ocamlres updated
[ocp-ocamlres] Installing new package description from git://github.com/OCamlPro/ocp-ocamlres

+ opam pin --yes add --no-action --dev-repo ocplib-json-typed
[NOTE] Package ocplib-json-typed is already git-pinned to https://github.com/ocamlpro/ocplib-json-typed.git.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[ocplib-json-typed] https://github.com/ocamlpro/ocplib-json-typed.git updated

+ opam pin --yes add --no-action --dev-repo ocplib-resto
[NOTE] ocplib-resto is currently git-pinned to https://github.com/OCamlPro/ocplib-resto.git.
Proceed ? [Y/n] y
ocplib-resto is now git-pinned to https://github.com/OCamlPro/ocplib-resto

[ocplib-resto] https://github.com/OCamlPro/ocplib-resto updated
[ocplib-resto] Installing new package description from https://github.com/OCamlPro/ocplib-resto

+ opam pin --yes remove tezos-deps
tezos-deps is now unpinned from path /Users/user/tezos/src
+ opam pin --yes add --no-action tezos-deps /Users/user/tezos/src
Package tezos-deps does not exist, create as a NEW package ? [Y/n] y
tezos-deps is now path-pinned to /Users/user/tezos/src

[tezos-deps] /Users/edubai/tezos/src/ synchronized
[tezos-deps] Installing new package description from /Users/user/tezos/src

+ true
+ opam list --installed depext
# Installed packages for tezos:
depext  1.0.5  Query and install external dependencies of OPAM packages
+ opam depext tezos-deps
# Detecting depexts using flags: x86_64 osx homebrew
# The following system packages are needed:
#  - gmp
#  - leveldb
#  - libev
#  - libsodium
#  - lzlib
#  - openssl
#  - pkg-config
# All required OS packages found.
+ true
+ opam install tezos-deps

=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[tezos-deps] /Users/edubai/tezos/src/ already up-to-date
The following actions will be performed:
  ∗  install conf-openssl     1               [required by ssl]
  ∗  install ssl              0.5.4           [required by lwt_ssl]
  ∗  install lwt_ssl          1.1.0           [required by tezos-deps]
  ∗  install conduit-lwt-unix 1.0.2           [required by git-unix]
  ∗  install cohttp-lwt-unix  0.99.0          [required by git-unix]
  ∗  install git-unix         1.11.2          [required by tezos-deps]
  ∗  install irmin-unix       1.3.0           [required by tezos-deps]
  ∗  install tezos-deps       dev*  
===== ∗  8 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[cohttp-lwt-unix] Archive in cache
[conduit-lwt-unix] Archive in cache
[git-unix] Archive in cache
[irmin-unix] Archive in cache
[lwt_ssl] Archive in cache
[ssl] Archive in cache
[tezos-deps.dev] /Users/user/tezos/src/ already up-to-date

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] The compilation of conf-openssl failed at "pkg-config openssl".

#=== ERROR while installing conf-openssl.1 ====================================#
# opam-version 1.2.2
# os           darwin
# command      pkg-config openssl
# path         /Users/user/.opam/tezos/build/conf-openssl.1
# compiler     4.04.2
# exit-code    1
# env-file     /Users/user/.opam/tezos/build/conf-openssl.1/conf-openssl-66906-e7966f.env
# stdout-file  /Users/user/.opam/tezos/build/conf-openssl.1/conf-openssl-66906-e7966f.out
# stderr-file  /Users/user/.opam/tezos/build/conf-openssl.1/conf-openssl-66906-e7966f.err

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions were aborted
  ∗  install cohttp-lwt-unix  0.99.0
  ∗  install conduit-lwt-unix 1.0.2 
  ∗  install git-unix         1.11.2
  ∗  install irmin-unix       1.3.0 
  ∗  install lwt_ssl          1.1.0 
  ∗  install ssl              0.5.4 
  ∗  install tezos-deps       dev   
The following actions failed
  ∗  install conf-openssl 1
No changes have been performed

=-=- conf-openssl.1 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
=> This package relies on external (system) dependencies that may be missing. `opam depext conf-openssl.1' may help you find the correct installation for your system.
make: *** [build-deps] Error 4

**Comment by MiloDavis** [comment]
What does `openssl version` return?

**Comment by edubai** [comment]
I gave up on installing from source, I have switched to docker version which works fine. Unfortunately I don't have the log anymore as I have re-installed the OS.

**Comment by edubai** [comment]
I have tried again to compile from source in a new machine and same problem, re-opening issue.

**MacBook-Pro:src edubai$ make**
Makefile:274: .depend: No such file or directory
LINK environment_gen
GENERATING proto_environment.mli
OCAMLDEP (minutils.cmxa) mBytes.mli
OCAMLDEP (minutils.cmxa) hex_encode.mli
OCAMLDEP (minutils.cmxa) utils.mli
OCAMLDEP (minutils.cmxa) compare.mli
OCAMLDEP (minutils.cmxa) data_encoding.mli
OCAMLDEP (minutils.cmxa) RPC.mli
OCAMLDEP (minutils.cmxa) mBytes.ml
OCAMLDEP (minutils.cmxa) hex_encode.ml
OCAMLDEP (minutils.cmxa) utils.ml
OCAMLDEP (minutils.cmxa) compare.ml
OCAMLDEP (minutils.cmxa) data_encoding.ml
OCAMLDEP (minutils.cmxa) RPC.ml
OCAMLDEP (utils.cmxa) base58.mli
OCAMLDEP (utils.cmxa) cli_entries.mli
OCAMLDEP (utils.cmxa) data_encoding_ezjsonm.mli
OCAMLDEP (utils.cmxa) crypto_box.mli
OCAMLDEP (utils.cmxa) time.mli
OCAMLDEP (utils.cmxa) hash.mli
OCAMLDEP (utils.cmxa) error_monad.mli
OCAMLDEP (utils.cmxa) lwt_exit.mli
OCAMLDEP (utils.cmxa) logging.mli
OCAMLDEP (utils.cmxa) lwt_utils.mli
OCAMLDEP (utils.cmxa) lwt_pipe.mli
OCAMLDEP (utils.cmxa) IO.mli
OCAMLDEP (utils.cmxa) moving_average.mli
OCAMLDEP (utils.cmxa) ring.mli
OCAMLDEP (utils.cmxa) watcher.mli
OCAMLDEP (utils.cmxa) tezos_data.mli
OCAMLDEP (utils.cmxa) base58.ml
OCAMLDEP (utils.cmxa) error_monad_sig.ml
OCAMLDEP (utils.cmxa) error_monad.ml
OCAMLDEP (utils.cmxa) cli_entries.ml
OCAMLDEP (utils.cmxa) data_encoding_ezjsonm.ml
OCAMLDEP (utils.cmxa) time.ml
OCAMLDEP (utils.cmxa) hash.ml
OCAMLDEP (utils.cmxa) crypto_box.ml
OCAMLDEP (utils.cmxa) lwt_exit.ml
OCAMLDEP (utils.cmxa) logging.ml
OCAMLDEP (utils.cmxa) lwt_utils.ml
OCAMLDEP (utils.cmxa) lwt_pipe.ml
OCAMLDEP (utils.cmxa) IO.ml
OCAMLDEP (utils.cmxa) moving_average.ml
OCAMLDEP (utils.cmxa) ring.ml
OCAMLDEP (utils.cmxa) watcher.ml
OCAMLDEP (utils.cmxa) tezos_data.ml
OCAMLDEP (embedded_cmis.cmx) tezos_data.mli
OCAMLDEP (embedded_cmis.cmx) persist.mli
OCAMLDEP (embedded_cmis.cmx) context.mli
OCAMLDEP (embedded_cmis.cmx) protocol_sigs.mli
OCAMLDEP (embedded_cmis.cmx) proto_environment.mli
OCAMLDEP (embedded_cmis.cmx) register.mli
OCAMLDEP (compiler.cmxa) tezos_compiler.mli
OCAMLDEP (compiler.cmxa) tezos_compiler.ml
OCAMLDEP (compiler.cmxa) compiler_main.ml
OCAMLDEP (node.cmxa) p2p_types.mli
ocamlfind: Package `ssl' not found


`**MacBook-Pro:src edubai$ opam install ssl**
The following actions will be performed:
  ∗  install   conf-openssl     1             [required by ssl]
  ∗  install   ssl              0.5.4 
  ↻  recompile conduit-lwt-unix 1.0.2         [uses ssl]
  ↻  recompile cohttp-lwt-unix  0.99.0        [uses conduit-lwt-unix]
  ↻  recompile git-unix         1.11.2        [uses conduit-lwt-unix]
  ↻  recompile irmin-unix       1.3.0         [uses git-unix]
===== ∗  2   ↻  4 =====
Do you want to continue ? [Y/n] Y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[cohttp-lwt-unix] Archive in cache
[conduit-lwt-unix] Archive in cache
[git-unix] Archive in cache
[irmin-unix] Archive in cache
[ssl] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
⊘  removed   irmin-unix.1.3.0
⊘  removed   git-unix.1.11.2
⊘  removed   cohttp-lwt-unix.0.99.0
⊘  removed   conduit-lwt-unix.1.0.2
[ERROR] The compilation of conf-openssl failed at "pkg-config openssl".

#=== ERROR while installing conf-openssl.1 ====================================#
# opam-version 1.2.2
# os           darwin
# command      pkg-config openssl
# path         /Users/edubai/.opam/tezos/build/conf-openssl.1
# compiler     4.04.2
# exit-code    1
# env-file     /Users/edubai/.opam/tezos/build/conf-openssl.1/conf-openssl-3988-05296d.env
# stdout-file  /Users/edubai/.opam/tezos/build/conf-openssl.1/conf-openssl-3988-05296d.out
# stderr-file  /Users/edubai/.opam/tezos/build/conf-openssl.1/conf-openssl-3988-05296d.err



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions were aborted
  ∗  install cohttp-lwt-unix  0.99.0
  ∗  install conduit-lwt-unix 1.0.2 
  ∗  install git-unix         1.11.2
  ∗  install irmin-unix       1.3.0 
  ∗  install ssl              0.5.4 
The following actions failed
  ∗  install conf-openssl 1
The following changes have been performed
  ⊘  remove cohttp-lwt-unix  0.99.0
  ⊘  remove conduit-lwt-unix 1.0.2 
  ⊘  remove git-unix         1.11.2
  ⊘  remove irmin-unix       1.3.0 

=-=- conf-openssl.1 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
=> This package relies on external (system) dependencies that may be missing. `opam depext conf-openssl.1' may help you find the correct installation for your system.

The former state can be restored with:
    opam switch import "~/.opam/tezos/backup/state-20170905093214.export"



**MacBook-Pro:src edubai$ opam depext conf-openssl.1**
# Detecting depexts using flags: x86_64 osx homebrew
# The following system packages are needed:
#  - openssl
#  - pkg-config
# All required OS packages found.
**MacBook-Pro:src edubai$ brew install openssl pkg-config**
Warning: openssl 1.0.2l is already installed
Warning: pkg-config 0.29.2 is already installed

`

**Comment by MiloDavis** [comment]
What's the output of `opam depext conf-openssl.1`? Have you built Tezos in OS X Sierra previously and things no longer work after upgrading or is the first time you've tried to build Tezos?

**Comment by edubai** [comment]
Please check my last 7 lines for the output of `opam depext conf-openssl.1`.

I'm building Tezos for first time.

**Comment by MiloDavis** [comment]
I think this could be related to the fact that Apple has switched to FreeSSL from OpenSSL on High Sierra. This was mentioned on Homebrew issue tracker [thread](https://github.com/Homebrew/homebrew-core/issues/14418#issuecomment-308850249).

I think you should try installing and linking openssl from homebrew or macports. You could also potentially report this issue to the [OCaml package maintainer](https://github.com/savonet/ocaml-ssl/issues).

**Comment by al1p** [comment]
Hello, brew does not let you force link openssl to replace libreSSL by OpenSSL, but I managed to run "make build-deps"  on High Sierra with the following: 

`brew install openssl`
`export LDFLAGS="-L/usr/local/opt/openssl/lib"`
`export CPPFLAGS="-I/usr/local/opt/openssl/include"`
`export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"`

**Comment by edubai** [comment]
Thanks @al1p, that solved the problem for me, fully compiled from source and tezos node is now running.👍

**Comment by toots** [comment]
The whole issue should be fixed now.
