### ISSUE TITLE
when project will be released?

### ISSUE THREAD

**Issue by huzhihao2002** [tezos/tezos#126]
When will project be released, what's the target date?
When will Tezos first be listed on an exchange?
The website doesn't update long time.

**Comment by coventry** [comment]
Questions like this belong on the [subreddit](https://www.reddit.com/r/tezos/), [riot](https://riot.im/app/#/room/!xSkytNSHjMbykqqfFO:matrix.org), or perhaps the Tezos [community forum](https://forums.tezos.community/). This forum is for technical issues.

**Comment by huzhihao2002** [comment]
cool
