### ISSUE TITLE
JSON.of_buffer expected JSON value

### ISSUE THREAD

**Issue by catsigma** [tezos/tezos#127]
After I typechecked this [tz contract](https://github.com/catsigma/bettingwin/blob/master/contracts/bet.liq.tz)

The error appeared like this.
```
Error:
  RPC request returned malformed JSON:
    Path: http://127.0.0.1:8732/blocks/prevalidation/proto/helpers/typecheck_code
    Error: JSON.of_buffer expected JSON value
    JSON data:
      > {
      >   "error": [
      >     {
      >       "kind": "permanent",
      >       "id": "illTypedContractTypeError",
      >       "expectedParameterType": {
      >         "or": [
      >           [
      >             "nat",
      >             {
      >               "or": [
......
```
I don't know if it is cause by the too large size of the contract?

**Comment by MiloDavis** [comment]
I get the following warning/error when typechecking:

```
tcmalloc: large alloc 1932746752 bytes == 0x1814cc000 @  0x7fffa096c282 0x7fffa096b200 0x107c55b18 0x107c58fd9 0x107c596d4 0x107bdd286
```

Do you get the same error?

**Comment by catsigma** [comment]
I'm running the node though `alphanet.sh`, so I didn't get the error msg from terminal.
But It did crash the tezos-node in docker.

**Comment by MiloDavis** [comment]
I'm updating this with the link to the original contract that failed: https://github.com/catsigma/bettingwin/blob/3265fd57c83ff44713308f39a2af0f650c403274/contracts/bet.liq.tz

**Comment by klakplok** [comment]
It now works in master.
