### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by tzs1** [tezos/tezos#134]
I receive this error at make:
```
File "src/proto/jbuild", line 5, characters 9-39:
Error: Unknown constructor alias_rec
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by OCamlPro-Henry** [comment]
You should use a more recent version of `jbuilder` (`beta15` at least is expected). Did `make build-deps` report any failure ?

**Comment by tzs1** [comment]
>You should use a more recent version of jbuilder (beta15 at least is expected).

Thanks, I'll check it.

> Did make build-deps report any failure?

No

**Comment by tzs1** [comment]
Question. JBuilder Beta15 requires ocaml-version >= "4.02.3" (https://opam.ocaml.org/packages/jbuilder/jbuilder.1.0+beta15/), but we build on 4.04.2. Is it correct?

**Comment by OCamlPro-Henry** [comment]
Sure `4.02.3 < 4.04.2` :-)

**Comment by tzs1** [comment]
Sorry, I was looking at the last digit only :D
Thank you, build succeeded
