### ISSUE TITLE
tezos-client hash data doesn't detect different timestamp format -> signature check fails

### ISSUE THREAD

**Issue by something3** [tezos/tezos#148]
michelson contracts seem to accept both `"2017-12-13T04:49:00Z"` and `"2017-12-13T04:49:00+00:00"`
both are converted to `"2017-12-13T04:49:00Z"` (at some point) before being hashed by `H`

`tezos-client hash data` doesn't convert `"2017-12-13T04:49:00+00:00"` to `"2017-12-13T04:49:00Z"` so the resulting hash is different and signature check fails

**Comment by hclivess** [comment]
Thanks for noticing, cross-code signing is a common problem in starting projects it seems

**Comment by klakplok** [comment]
Fixed in master, by requiring to provide the type of the piece of data to hash.
