### ISSUE TITLE
Alphanet error on get balance

### ISSUE THREAD

**Issue by Jonybang** [tezos/tezos#159]
`./alphanet.sh client get balance for my_account`
```
Fatal error:
  Error in command line argument 4 (my_account)
  Invalid data
```
OS: Ubuntu 16.04, script started via docker

**Comment by 1ightningFury** [comment]
looks like you have no account or spelling my_account wrong

when i typed wrong i get:

```
Fatal error:
  Error in command line argument 4 (myaccount)
  no contract or key named myaccount
  bad contract notation
  Economic error:
    Invalid contract notation "myaccount"
```

`./alphanet.sh client list known contracts`

to show known contracts
