### ISSUE TITLE
Error in assert_endorser function in alphanet.sh

### ISSUE THREAD

**Issue by fredcy** [tezos/tezos#160]
At https://github.com/tezos/tezos/blob/7ebac0a319daf241fda7460c09d40cf9ddb7e19f/scripts/alphanet.sh#L303 where it reads `check_baker` it should instead be `check_endorser`.

@redeyedcat on the #tezos dev channel first reported the error.

**Comment by MiloDavis** [comment]
This is fixed as of 1ec1f501a4ab9e41fa3defed6113fdbcf188c0b4
