### ISSUE TITLE
Get balance issue

### ISSUE THREAD

**Issue by lexxor79** [tezos/tezos#166]
**Hi Tezos team,**

First, I would like to thank you for your good work !

I started working/trying the alphanet in order to understand how baking on Tezos blockchain works.

I succeed to run an alphanet node on linux Ubuntu 16.04 but I have an issue when I enter this command line :
sudo ./alphanet.sh client get balance for TZ1jG3JBHatvK1Zu6UF7dZM33EncAEirNiGk

**result message :** 
Fatal Error:
RPC request failed:
Path: http://127.0.0.1:8732/blocks/prevalidation/proto/context/contracts/TZ1jG3JBHatvK1Zu6UF7dZM33EncAEirNiGk/balance
HTTP Status: 404 (Not Found)

Someone can help me ?

Thank you again and see you at lunch !

**Comment by joybuckley** [comment]
Same issue here ! thanks for your help

**Comment by joybuckley** [comment]
that's why ! https://github.com/tezos/tezos/tree/alphanet#missing-account-my_account

**Comment by lexxor79** [comment]
Your link send me back on the Alphanet home page !

**Comment by lexxor79** [comment]
Sorry I got it ! thanks for your help !
