### ISSUE TITLE
How can I join alphanet since master branch compilation

### ISSUE THREAD

**Issue by munakaya** [tezos/tezos#167]
master branch compilation is done successfully.
But my node does not seem to get connection with other node.

What should I do?
I went thru "http://doc.tzalpha.net/introduction/alphanet.html"
I do not get hint except docker way.

And below command does not work.

> If you want to stake (see below for more details), you will also have to run:
> 
> 
> test@test-VirtualBox:~/tezos$ ./tezos-client launch daemon
> Error:
>   Unrecognized command.
>   Try using the man command to get more information.
> 
> Usage:
>   tezos-client [global options] command [command options]
>   tezos-client --help (for global options)
>   tezos-client [global options] command --help (for command options)
> 
> To browse the documentation:
>   tezos-client [global options] man (for a list of commands)
>   tezos-client [global options] man -v 3 (for the full manual)
> 
> Global options (must come before the command):
>   -d --base-dir <path>: client data directory
>   -c --config-file <path>: configuration file
>   -t --timings: show RPC request times
>   -b --block <hash|tag>: block on which to apply contextual commands
>   -p --protocol <hash>: use commands of a specific protocol
>   -l --log-requests: log all requests to the node
>   -A --addr <IP addr|host>: IP address of the node
>   -P --port <number>: RPC port of the node
>   -S --tls: use TLS to connect to node.
> test@test-VirtualBox:~/tezos$ 
> 

test@test-VirtualBox:~/tezos$ ./tezos-node run --rpc-addr 127.0.0.1
Feb 24 23:14:30 - node.main: Starting the Tezos node...
Feb 24 23:14:31 - node.main: Peer's global id: idstpaNsJg8Hiy8EMkav28eGUwKmz5
Feb 24 23:14:31 - node.worker: bootstraping chain...
\Feb 24 23:14:31 - node.validator: activate chain NetXj4yEEKnjaK8
Feb 24 23:14:31 - p2p.maintenance: Too few connections (0)
Feb 24 23:14:31 - node.main: Starting the RPC server listening on port 8732.
Feb 24 23:14:31 - node.main: The Tezos node is now running!
Feb 24 23:14:41 - p2p.maintenance: Too few connections (0)
Feb 24 23:14:51 - p2p.maintenance: Too few connections (0)
Feb 24 23:15:01 - p2p.maintenance: Too few connections (0)

**Comment by edubai** [comment]
Did you change the git branch from Master to Alphanet? It’s the most common problem for no connection.

**Comment by munakaya** [comment]
There is no way to run alphanet  on masterbanch?

**Comment by justmustone** [comment]
test@test-VirtualBox:~/tezos_alpha$ sudo ./alphanet.sh restart 
Saving the secrets into '/home/test/.tezos-alphanet/secret keys'...

WARNING: THE SECRET KEYS FILE IS UNENCRYPTED!!!

Stopping the container...  done
alphanet: Pulling from tezos/tezos
Digest: sha256:d8c5bb3894a453fb87dede7783f6438aab48201ef7b2ba6171b18c596991bb11
Status: Image is up to date for tezos/tezos:alphanet
The script is up to date.
Error: No such container: tezos-alphanet
Launching the docker container...
Restoring the peer identity from '/home/test/.tezos-alphanet/identity.json'...
Restoring the secret keys from '/home/test/.tezos-alphanet/secret keys'...
Peer_id: idrikHdjkESnn1iqzVoJYWhJ6uiupN. Proof of work is higher than 24.00.
Waiting for the node to synchronize with the network...
Current head: BLockGenesisGe (2017-10-19T00:00:00Z)


And in another terminal,
test@test-VirtualBox:~/tezos_alpha$ sudo ./alphanet.sh client get balance for my_account
Unrecognized command. Try using the 'man' command to get more information.
test@test-VirtualBox:~/tezos_alpha$ 


Why command does not work??

**Comment by munakaya** [comment]
I  followed "https://github.com/tezoscommunity/faq/wiki/How-to-build-an-alphanet-node-quickly" and it worked for me. Still I do not know how to run without docker.
