### ISSUE TITLE
"error: Integer literal exceeds the range of representable integers of type int" in files gas.ml and data_encoding.ml

### ISSUE THREAD

**Issue by maxtez-raspbaker** [tezos/tezos#169]
I tried to compile Tezos from the master node (March/12) with OCaml 4.06.1 and I stumbled in the above error in the following files:

src/lib_data_encoding/data_encoding.ml (line 194 and line 204)
src/proto_alpha/lib_protocol/src/gas.ml (line 239 line 246)

I am no expert but should the limits be something like this:
min_int (lowest signed int) -1073741824
max_int (greatest signed int) 1073741823

while it appears that in the two files the unsigned limit value has been used:
greatest unsigned int 2147483647

just for testing I replaced 2147483647 with the signed limit in the two files, compilation was successful but with the command: "tezos-node run" I got the following error:

Json_encoding.Cannot_destruct(_)

which is triggered by the first of the above two files (src/lib_data_encoding/data_encoding.ml) on line 284. 
Hope this makes sense

**Comment by munakaya** [comment]
Why don't you build as an alphanet branch. You can join the alphanet with your own node.

**Comment by maxtez-raspbaker** [comment]
done that almost 3 months ago (see the history here https://forums.tezos.community/). It is about time to see if RPI3 can also take the new version of Tezos running on the zeronet. And the (preliminary) answer is yes it can, but things are a bit different compared to the alphanet, more testing is needed

**Comment by klakplok** [comment]
Constants have been changed in master.
