### ISSUE TITLE
Michelson docs: integer overflow semantics unclear

### ISSUE THREAD

**Issue by bshanks** [tezos/tezos#23]
Each of the following should be explained in the Michelson docs:

What is meant by 'cycling semantics for overflows' in NEG, ABS, ADD, SUB? For example, if i ADD 0x0000000000000001 0xFFFFFFFFFFFFFFFF, then what is the result?

If MUL is unchecked for overflows, then what happens if there is an overflow. For example if i MUL 0x0000000000000002 0xFFFFFFFFFFFFFFFF, then what is the result?

I assume that CAST behaves according to the masking functions in the box at the top of the section, but it would help to say that explicitly under CAST.

**Comment by tezos** [comment]
We've since moved to arbitrary precision integers and naturals, but haven't updated the document yet.
