### ISSUE TITLE
validation node - p2p.maintenance: Too few connections

### ISSUE THREAD

**Issue by buckshot32** [tezos/tezos#29]
Greetings-
running ubuntu 16.10. , used downloaded sodium 1.0.11 (DEV & 18), build.deps & make ran perfectly.
identity generate 24 ran perfectly.
tezos node run - throws error- p2p.maintenance: Too few connections
as soon as the node starts
any ideas?
thanks!

**Comment by OCamlPro-Henry** [comment]
By defaut, the P2P layer tries to establish 20 connections minimum, it will display this message until then. If you are running a node on your own, you may safely ignore this message. If you are running the `alphanet`, the message should disseappear after a few minutes. But until then, the node is already  properly validating block.

Anyway, you might avoid this message either by:
- passing `--sandbox`, if you want to run a single node (without P2P network)
- passing `--connection 5` to reduce the number of expected connection.

**Comment by buckshot32** [comment]
Greetings again Grégoire - many thanks, the issue is resolved.
my alphanet node is now working as expected:
Node is running
Baker is running
Endorser is running
homeboy1@ubuntu:~$ sudo ./alphanet.sh client get balance for my_account
100,000.00_ 
if there is anything i can test or help with in alphanet from Atlanta, do let me know.
great job with the crowdfund!
