### ISSUE TITLE
DDOS testing

### ISSUE THREAD

**Issue by posix4e** [tezos/tezos#30]
This may be the wrong forum for this, but I am curious what type of DDOS testing against the alpha network has been tried.

**Comment by aaronwinter** [comment]
@tezos I'm curious as well

**Comment by tezos** [comment]
We thought a lot about resistance against layer 7 DDOS when designing the peer to peer interface and the network shell. We've also used the "evil client" to simulate some denial of service attacks, focusing on tricking nodes to waste bandwith and computation. However, we have not done it at scale yet, but stress testing is on the roadmap.

**Comment by pmetzger** [comment]
Since this is not a report of a specific bug, I'd suggest that the issue be closed.
