### ISSUE TITLE
Please bail me out of password mistake

### ISSUE THREAD

**Issue by toothlessdragon** [tezos/tezos#32]
Hi Tezos Devs,

I really believe in what you guys are doing, bringing ocaml and functional programming to crypto.  Thank you!

As such, I contributed 1 BTC into the crowdsale, for wallet 1193, hoping to receive 6000 tezzies.

**Almost instantly, I lost the password to wallet 1193.**

So I was very sad for a while, and then I created wallet 48880 and contributed 1 BTC for 6000 tezzies.

If you would PLEASE credit the tezzies from wallet 1193 to wallet 44880 (so it has 12,000 total) I would appreciate it to no end.  If the email address is public, you'll notice that both wallets are associated with the same email: oojensen@alumni.stanford.edu.  That is the same email as the one that is public on this github account.

If it helps
wallet 1193 has public key hash tz1L4g28vJzijS2Zptv8rPZb7bMDj3CzGPGD
wallet 44880 has public key hash tz1d3chghTEK1s6KEA4zkj2DBYVRW67wnoHw

This is not a scam, I'm just having a bad morning I guess.  If any of you guys are Shakespeare buffs, this seems relevant:

> "In my school days, when I had lost one shaft,
> I shot his fellow of the selfsame flight
> The selfsame way with more advisèd watch
> To find the other forth—and by adventuring both,
> I oft found both. I urge this childhood proof
> Because what follows is pure innocence.
> I owe you much, and, like a willful youth,
> That which I owe is lost. But if you please
> To shoot another arrow that self way
> Which you did shoot the first, I do not doubt,
> As I will watch the aim, or to find both
> Or bring your latter hazard back again
> And thankfully rest debtor for the first."

In fact, you guys could make a blog post out of this.  Here, I'll write a draft

> **Benevolent Tezos Foundation aids hapless cryptocurrency noob**
>
> The Tezos foundation announced today that it intends to restore 6000 XTZ to @toothlessdragon. 
 "I'm very grateful to the Tezos foundation for answering my plea," says @toothlessdragon, "6000 XTZ is a lot for someone like me to lose".  After hearing from @toothlessdragon on github, the Tezos foundation worked out a way to move the lost cryptocurrency to a wallet that the poor fellow could access.
>
> "We knew we had to help him out when he quoted Shakespeare" someone at the Tezos foundation might have said.  "Then he did something even more absurd and drafted a fake press release, complete with fake quotes.  Some of us didn't think it was funny but a few got the joke."
>
> The Tezos foundation cautions that they cannot intervene for everyone who loses their password.  "This time, it seemed like by helping out we could get publicity on how careful you need to be when dealing with cryptocurrencies.  Heck, @toothlessdragon went to Stanford, which is to say that mistakes can happen to anyone."  After hearing from the foundation, @toothlessdragon said "I've really learned my lesson here and I'm grateful to the foundation.  It's important to verify that every critical piece of information is saved and backed up to paper or a secure usb."

**Comment by HEYSUNKIM** [comment]
체크  불일치 는  어떻게  하나요?

**Comment by HEYSUNKIM** [comment]
지갑 2 개로  기부 했는데   공개키 하나는  체크  불일치네요.너무슬퍼요

**Comment by HEYSUNKIM** [comment]
BTC  2 개가 불일치로

**Comment by tezos** [comment]
I'm super sorry about this, but please get in touch with contact - at - tezos.com regarding fundraiser related issue, as this is an issue tracker for the Tezos codebase.

**Comment by HassanAmad** [comment]
Ok is this "password checking" thing real? I want to make sure that Im not being scammed here. How do I ensure my password is correct without being scammed?

**Comment by hclivess** [comment]
"this is not a scam" lol

**Comment by aaronwinter** [comment]
@HassanAmad There's only one password checker that is "official", it is [https://www.tezos.com/pwcheck.html](https://www.tezos.com/pwcheck.html). It is better to run it offline on a trusted machine.

FYI: `MD5 (pwcheck_full.html) = 781603aefbf0dfd5ac3bc030e7e0d3e7`
