### ISSUE TITLE
tezos fund not deposited yet

### ISSUE THREAD

**Issue by shahed17** [tezos/tezos#33]
hi there, 
i have deposited minimum amount last night via xrp/btc with shape shift but still my fund hasn't been added to my account , i really dont have clue what happening , my xrp already deducted and i have followed all instructions , could you please let me know the know the reason

**Comment by tnarnold** [comment]
My bitcoin wallet too. No tezos yet. 3G57nqd5hVZyWNKy92EiQyXYiJHs764rTq

**Comment by aedg** [comment]
在不

**Comment by aedg** [comment]
至少0.1比特

**Comment by shahed17** [comment]
there is no contact details with tezos , do you guys have any ? please let me know how to acknowledge the tezos team

**Comment by aedg** [comment]
你是那个国家的

**Comment by aedg** [comment]
我这边也查不到，我比特也打过去了

**Comment by HEYSUNKIM** [comment]
지갑 2 개로 비트 넣었는데  아직확인 안됨
https://guides.github.com/features/mastering-markdown/

**Comment by tezos** [comment]
I'm super sorry about this, but please get in touch with contact - at - tezos.ch regarding fundraiser related issue, as this is an issue tracker for the Tezos codebase.

P.S. contact details are given in the Tezos overview document, on the last page.

**Comment by tezos** [comment]
I'm super sorry about this, but please get in touch with contact - at - tezos.ch regarding fundraiser related issue, as this is an issue tracker for the Tezos codebase.

P.S. contact details are given in the Tezos overview document, on the last page.
