### ISSUE TITLE
no addtional transaction

### ISSUE THREAD

**Issue by paperstory** [tezos/tezos#36]
I already did 1time for funding, and today, I did 2nd time transaction.
But it doesn't show addtional transaction.

Ethereum transaction was done.

Please check this.
Thank you!

My Ethereum wallet address is 
0x7F9CEdeBae9bB65Fc790AD908dc724DffC664B4B

**Comment by pmetzger** [comment]
Howdy. This is the github issue tracker, which is where you report bugs in the code in Tezos. It is not a place for complaining about problems in the crowdsale. You should follow the instructions on the Tezos web site for that. If you want to comment on bugs in the tezos codebase, this is where you should do it.

**Comment by paperstory** [comment]
hello.
I didnt know that!
Thank you for advise!
have a good day!

2017-07-03 1:57 GMT+09:00 Perry E. Metzger <notifications@github.com>:
