### ISSUE TITLE
There is no documentation in the code nor with the code.

### ISSUE THREAD

**Issue by PavelNiedoba** [tezos/tezos#37]
I'm I missing something ? I expect that there is at least some documentation, but here  I didn't find single line of documentation. Considering the fact, that you are running fund-rising I doubt that this code can be ever finished.

**Comment by pmetzger** [comment]
Why would the fact that they are doing fund raising make it impossible to write documentation or finish the code?

BTW, there's a directory called "docs" you may have missed. It's inadequate, but the contents are more than one line long.

**Comment by PavelNiedoba** [comment]
Documentation is supposed to be written with the code. Without it it's impossible for new developers to join the project. If the code is about 3MB and all docs found in it is 66 lines (38 sloc) 3.51 KB then I have to recommend to every potential fund riser to reconsider, because the project seems highly non-professional and there is high risk, that it will never be finished.

**Comment by pmetzger** [comment]
"the project seems highly non-professional and there is high risk, that it will never be finished" —
The Tezos alphanet is already up and running so it is obvious the code actually works, though it is not yet fully stable and won't be for some months.

"Documentation is supposed to be written with the code" — some people choose not to do things that way. The Linux kernel has precious little internal documentation, and yet it is a much larger codebase that is quite thoroughly operational.

Regardless, I don't think this is a bug report in any conventional sense, and it doesn't belong here. If you want to complain that you don't like Tezos, there are many places to do that. This is a location for concrete bug reports.

**Comment by PavelNiedoba** [comment]
I get your point. I hope you can get Ocaml programmers now, wish you luck anyway. I would add this coin in my exchange wallet is ready.

**Comment by dannywillems** [comment]
@PavelNiedoba OCaml, not Ocaml :)

**Comment by dvoytik** [comment]
@pmetzger 39 MiB of linux/Documentation is little?
