### ISSUE TITLE
Can somebody help me to find Support on ICO Tezos ???

### ISSUE THREAD

**Issue by boatswainanton** [tezos/tezos#38]
I went my money to Tezos ICO on the wallet yesterday, and i can not find them. Transaction on block chain now is 86. Where can i find Support???

**Comment by ucfyao** [comment]
me  too ，how about it

**Comment by adammalak** [comment]
hi my problem is i dont found support , i by 0.1 btc , the first i sent 0.034 btc and after i sent 0.07 btc, when i verified my contribute , i found only 402 tezos for 0.07 btc , an  for other one  no receive , normally   598

**Comment by vbmithr** [comment]
Please wait till the end of the ICO in order for things to be settled. The contribution you sent will either count as a contribution and be allocated XTZ at the expected rate, or be refunded.

**Comment by vbmithr** [comment]
Please do not send messages on this bugtracker which is reserved for development (source code).

**Comment by hclivess** [comment]
MY GOD, THESE NOOBS

**Comment by OCamlPro-Henry** [comment]
Question about the crowdsale should be directed toward contact@tezos.ch

**Comment by pmetzger** [comment]
Someone should close this issue, it is not a bug in the code (or a similar technical problem.)
