### ISSUE TITLE
Status of alphanet

### ISSUE THREAD

**Issue by fredcy** [tezos/tezos#39]
The alphanet seems to be stuck at blocks that are four days old. Is the alphanet going to be managed at all during the crowdfund period? Now that the Slack is gone, how can we communicate with the core dev team?

**Comment by OCamlPro-Henry** [comment]
Indeed, we are not giving much attention to the alphanet during the crowdsale, but our nodes are running fine.

Regarding, the prefered communication channel we haven't decided yet. I'm currently on IRC `tezos@freenode`. And, this bugtracker looks OK to me., as a temporary solution at last.

**Comment by fredcy** [comment]
I restarted my Tezos node and it did sync correctly (near as I can tell).

I will use IRC for now as you suggested.  Thanks.
