### ISSUE TITLE
LOSSE MY SECRET KEY OF TEZOS WALLET

### ISSUE THREAD

**Issue by samu89** [tezos/tezos#40]
Hello,

somebody can help how to recover my secret key of my wallet tezos, I delete by mistake, and now i can verified my contribution on tezos site, i just have the confirmation that i send of myetherwallet 

thanks

**Comment by pmetzger** [comment]
This is a bug tracker for the Tezos source code. It is not a place to get help with problems with the ICO. For that, please email "contact at tezos.ch".

**Comment by pmetzger** [comment]
(And as this isn't about a bug in the code, I'd suggest that someone close the issue.)
