### ISSUE TITLE
i didn't get my bonus for contribution

### ISSUE THREAD

**Issue by fidaaayoub** [tezos/tezos#44]
hello team.

i have contributed in the first few hours (in the 20% bonus period). (by BTC).  in the bonus calculator, it reflected the amount of bonus i am getting. 
i have done another contribution by ETH, calculator was showing 10% bonus rate..... 
when i check my contribution status on the tezos link, , it just shows both transactions, but the tezos amount with out any bonus.

any idea if bonus will come afterwards?

Thanks

**Comment by pmetzger** [comment]
Howdy! This is a bug tracker for the Tezos source code, not a way to contact the Tezos people about problems with the crowdfunding campaign. Please email "contact at tezos.ch" to talk to the right people.

And I'd suggest that this issue be closed.

**Comment by fidaaayoub** [comment]
Do you know the mail ID

Best Regards,

Fidaa Ayoub, PMP

**Comment by pmetzger** [comment]
I wrote it in my comment. "contact at tezos.ch"
Replace the "at" with an at sign.

**Comment by fidaaayoub** [comment]
Thanks @pmetzger  i have just sent them an email.
