### ISSUE TITLE
F# implementation

### ISSUE THREAD

**Issue by alenny811** [tezos/tezos#46]
Hi,
I have a question to dev team regarding F#.
It is known that Ocaml is the "father" of F# and the languages are very similar.
Also F# has some advantages like variety of IDEs (VS for mac and windows, monodevelop and ionide.io), wider community, dozens of .net libraries and gorgeous fable.io - F# to javascript compiler.

Now that we have cross-platform production-ready .net core framework from MS (alongside with mono) what are the reasons not to use F# for Tezos development ?

Thanks

**Comment by OCamlPro-Iguernlala** [comment]
I see at least one (two) reasons:

reason 0: Most (all) of Tezos developers are from OCamlPro

reason 1: I don't know if F# is now as mature as OCaml regarding features (GADTs, functors, ...) that are heavily used in Tezos

**Comment by dakk** [comment]
@alenny811 regarding your first motivation about F#, there are plenty of IDE support even of ocaml; the merlin ocaml auto-completor could be integrated in every IDE which supports plugins. I personally use visual-studio-code with merlin, it's really a good tool.
About Ocaml2javascript currently there are two solutions for it: js_of_ocaml and bucklescript (personally I prefer the second).
Ocaml may not have as much libs as .net world, but opam has a variety of useful libraries: https://opam.ocaml.org/packages/

**Comment by pmetzger** [comment]
Regardless, this doesn't seem like a bug report.

Maybe there's a need for a (technical topics only) discussion mailing list?
