### ISSUE TITLE
Transfer cancelled can I re-initiate are retrieve ethereum into my coinbase/gdax wallet?

### ISSUE THREAD

**Issue by racsix** [tezos/tezos#47]
Hi I initiated a transfer in ethereum. Unfortunately all GDAX requested was a wallet number it never requested a transaction number or gas limit. so when I entered the Tezos contract number I assumed the next step of the transfer would be transaction and gas info for association purposes. I have all of the cancelled transaction information from Ethereum.io if this helps.

**Comment by vbmithr** [comment]
Hi. There is nothing Tezos can do. You need to contact GDAX support to get your GDAX account re-credited.

**Comment by racsix** [comment]
I did and am waiting on their response. I was working both angles. Because the mistake really belongs to no one but me. I got in a hurry and frankly just screwed up.

**Comment by pmetzger** [comment]
Regardless, this isn't Tezos support. It is, rather, a bug tracker for bugs in the Tezos source code. This is not an appropriate place to request help with anything other than bugs in the code.

Someone should close this ticket.
