### ISSUE TITLE
Where are my money?

### ISSUE THREAD

**Issue by Plasmmer** [tezos/tezos#48]
Sorry for opening a GitHub issue for this, but the "Help" section only shows me a lot of explanations choosen by someone, but my question isn't included and the page doesn't have any contact email!

I'd invested 0.1631 ETH (107.28 XTZ), but it shows the balance is 0.

<img src="https://image.prntscr.com/image/iRAH9F_BS1aaSKOLS5cIdA.png"/>

**Comment by pmetzger** [comment]
This is not the help system for people participating in the ICO. It is a ticket system for problems with the Tezos source code.

Please send email to "contact at tezos.ch" instead.

**Comment by pmetzger** [comment]
And someone please close this ticket.

**Comment by Plasmmer** [comment]
How did you discovered the email?

**Comment by pmetzger** [comment]
It was on the web pages, on twitter, and described in previous trouble tickets people opened for similar reasons. I suspect it was probably mentioned elsewhere as well.
