### ISSUE TITLE
Why mandatory ipv6?

### ISSUE THREAD

**Issue by bodymindarts** [tezos/tezos#49]
I wanted to run a node on a popular public cloud provider and just noticed its not going to work because of the lack of support for ipv6.
I could move to another provider but I'd also like to understand why ipv6 is mandatory. Would it be possible to support ipv4-only as well?

**Comment by tezos** [comment]
ipv6 isn't mandatory, the node works fine with ipv4. Are you getting some kind of error message?

**Comment by bodymindarts** [comment]
There are a number of places where sockets are created with the `PF_INET6` setting. Like [here](https://github.com/tezos/tezos/blob/8724626fdd27f6de6a19576f30bf91b7199919e8/src/node/net/p2p_discovery.ml#L56) and [here](https://github.com/tezos/tezos/blob/6a63f871b288d2e528145a270fe7ff6f14f9023a/test/p2p/test_p2p_io_scheduler.ml#L22) and [here](https://github.com/tezos/tezos/blob/6a63f871b288d2e528145a270fe7ff6f14f9023a/src/node/net/p2p_connection_pool.ml#L737).

As far as I can tell this setting will cause the `Unix.EAFNOSUPPORT` error when trying to bind to an interface without ipv6 support. 

This is the error:
```
Jul 18 08:22:46 - node.main: Starting the Tezos node...
Jul 18 08:22:46 - node.main: Peer's global id: idqZAhAXSG5V2zpiiu7ehwBvrZV3Rn
Jul 18 08:22:46 - node.worker: bootstraping network...
Jul 18 08:22:46 - p2p.welcome: Cannot accept incoming connections
Jul 18 08:22:46 - p2p.welcome:   Unix error in socket: Address family not supported by protocol
tezos-node: internal error, uncaught exception:
            Unix.Unix_error(Unix.EAFNOSUPPORT, "socket", "")
            Raised at file "src/core/lwt.ml", line 805, characters 16-23
            Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
            Called from file "node/main/node_run_command.ml", line 195, characters 8-24
            Called from file "src/cmdliner.ml", line 1303, characters 27-34
            Called from file "src/cmdliner.ml", line 1350, characters 17-26
```

**Comment by tezos** [comment]
Ah you are correct, it does require kernel support for ipv6, but you don't actually need ipv6 connectivity to run the node.
