### ISSUE TITLE
RPC service should allow cross-origin requests (CORS)

### ISSUE THREAD

**Issue by fredcy** [tezos/tezos#5]
I'm working on a browser client that accesses the Tezos JSON API. I find that XMLHttpRequest() calls from my client are rejected in Chrome with this message:

    XMLHttpRequest cannot load http://localhost:8732/blocks. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

Here is a simple HTML document with Javascript that demonstrates the problem. It assumes that tezos-node is serving RPC on port 8732 of localhost.

```html
<!DOCTYPE HTML>
<html>
    <body>
        <script type="text/javascript">
         function listener () { console.log(this.responseText); }

         var req = new XMLHttpRequest();
         req.addEventListener("load", listener);
         req.open("GET", "http://localhost:8732/blocks");
         req.send();
        </script>
    </body>
</html>
````

**Comment by fredcy** [comment]
I discussed this issue with 'damian' on the Tezos Slack channel.

I am working around the problem for now using the "Allow-Control-Allow-Origin: *" extension for Chrome which forges a response header allowing cross origin access.

**Comment by fredcy** [comment]
The above workaround is OK for simple GET requests to the RPC service but I'm now finding that POST requests via XHR are failing even with that extension forging the CORS headers.

What I see in the Chrome console is this:

    XMLHttpRequest cannot load http://localhost:8732/blocks. Response for preflight has invalid HTTP status code 405

The network trace shows the browser sending an OPTIONS request as the CORS "preflight". That's resulting in a 405-not-found response from the tezos node service with an 'Allow: POST' header in that response.

**Comment by fredcy** [comment]
Here's an example of the latter problem:

```html
<!DOCTYPE HTML>
<html>
    <body>
        <script type="text/javascript">
         var req = new XMLHttpRequest();
         req.open("POST", "http://localhost:8732/blocks");
         req.setRequestHeader("Content-Type", "application/json");
         req.onreadystatechange = function() {
             console.log("change", [ req.readyState, req.status, req.responseText ]);
         }
         var body = "{ \"operations\": true }";
         req.send(body);
        </script>
    </body>
</html>
```

If I remove the `req.setRequestHeader()` call then it works OK.

**Comment by tezos** [comment]
Fixed a while back :)

**Comment by fredcy** [comment]
Yes, CORS has been working fine for me in the alphanet versions of the Tezos node. (However, the alphanet is not currently processing any blocks.)
