### ISSUE TITLE
Provide documentation on what is formally verified in tezos 

### ISSUE THREAD

**Issue by posix4e** [tezos/tezos#53]
There's a lot of confusion about this online.

**Comment by pmetzger** [comment]
As I understand it, currently there's a formal semantics for most of Michaelson and most of the system is designed for formal verification, but there are no proofs of correctness of any of the implementation, _yet_. In the long run, as I understand it, the goal is to verify everything.

**Comment by pmetzger** [comment]
But yah, probably it would be useful to have something in a README.

**Comment by posix4e** [comment]
Thanks ! I secretly knew that but am done repeating it to others :)

**Comment by tezos** [comment]
This should be a FAQ on the website, not in the codebase.
