### ISSUE TITLE
Intermittent error with alphanet `update_script`

### ISSUE THREAD

**Issue by ktorn** [tezos/tezos#54]
The alphanet script includes an option `update_script` that updates itself from the latest docker image.

This option occasionally fails with the following error:

```
$ ./alphanet.sh update_script
alphanet_next: Pulling from tezos/tezos
Digest: sha256:b4133722e783588e0e0c98a3e8333177d50a6c8b7ed8f0bc9a4c3fa071cdd2bb
Status: Image is up to date for tezos/tezos:alphanet_next
Error response from daemon: Error: driver aufs is returning inconsistent paths for container e646832b3790d0c285d80ed166b955e698b82d4aee56157e8ee352a73b8b5541 ('/var/lib/docker/aufs/mnt/7200fa64e75277044b35f7127d73d7987e53192fec221b00d68eec300e85b280' then '/var/lib/docker/aufs/diff/7200fa64e75277044b35f7127d73d7987e53192fec221b00d68eec300e85b280')
```

It seems to be because the temporary docker containter created by this action sometimes doesn't live long enough for the file to be copied out. Although not an ideal fix, seem that replacing the entrypoint `/bin/true` with a `sleep 1` seems to fix it for the most part.

Since this file is not yet in the github repo, here's a [patch](http://termbin.com/wygy).

**Comment by tezos** [comment]
Fixed, thank you for the report!
