### ISSUE TITLE
Documentation: transfers executed by a contract before it fails

### ISSUE THREAD

**Issue by fab13n** [tezos/tezos#66]
It's not clear from the doc `src/proto/alpha/doc/language.md` what happens when a contract:

1. performs an external call with `TRANSFER_TOKENS`;
2. then `FAIL`s

Is the called contract call still executed on the blockchain, or is it canceled?

**Comment by tezos** [comment]
In the current semantic, if there is any `FAIL` at any point, the entire transaction fails. We're thinking a bit through that semantic to allow failure in called contracts, though there are programming patterns that can guard through that.

**Comment by fab13n** [comment]
As long as the default behavior is to fail when a subcontract fails, it seems OK.

But whatever the chosen/current semantics is, it is important to clearly state it in the doc.
