### ISSUE TITLE
"run program" unexpectedly reverses lists

### ISSUE THREAD

**Issue by danrobinson** [tezos/tezos#69]
For example, executing the identity contract reverses a list, when it should have no effect on it:

```
./tezos/tezos-client run program 'text:parameter (list string); return (list string); storage unit; code{};' on storage 'Unit' and input 'List "test" "1" "2" "3"'
storage
  Unit
output
  (List "3" "2" "1" "test")
```

This bug probably obscured the fact that the example contract that _should_ reverse a list, https://github.com/tezos/tezos/blob/2d0f84f1faee5a3d611c6a18f709a4f596aa76d3/test/contracts/reverse.tz, also has a bug. The third instruction, `SWAP`, means that the loop is executed on an empty list, rather than on the list provided as a parameter. As a result, the loop is only run once, and the initial list is returned unchanged. 

(The implementation at http://www.michelson-lang.com/ has a different bug—it is missing a `DIP {SWAP}` in the `IF_CONS` body. Similarly, as a result, the loop is only run once and the initial list is returned unchanged.)

**Comment by tezos** [comment]
Fixed in an upcoming commit, thank you for the report !
