### ISSUE TITLE
Client crashes when ~/.tezos-client/logs/requests is unwritable, taking node down with it

### ISSUE THREAD

**Issue by fredcy** [tezos/tezos#7]
My ~/.tezos-node/logs/requests directory was owned by root for some reason. That causes tezos-client to crash without any error message. Not only that, tezos-node crashes too, apparently because the socket connection fails unexpectedly. Seems like two distinct defects to me.

This happens on the newest commit today, 9ca8cd2. The earliest commit where I see the problem is 6594959 (Dec 1).

To replicate, running as non-root user:

`sudo chown root ~/.tezos-client/logs/requests`

`./tezos-node --sandbox ../data --rpc-addr ::1:8732`

`./tezos-client rpc list`

**Comment by tezos** [comment]
We've deactivated client logs for a while, but will make sure to fix when reactivating
