### ISSUE TITLE
MAC OS Make build-deps failing,  trouble switching to verson 4.04.2

### ISSUE THREAD

**Issue by Nishkixs** [tezos/tezos#70]
```
~/Desktop/testnet/tezos (master)$ opam switch tezos --alias-of 4.04.2
# To setup the new switch in the current shell, you need to run:
eval `opam config env`
~/Desktop/testnet/tezos (master)$ eval `opam config env`
~/Desktop/testnet/tezos (master)$ make build-deps

   Unexpected compiler version (4.04.0)
   You should use ocaml-4.04.2.

make: *** [build-deps] Error 1
```
~/Desktop/testnet/tezos (master)$

**Comment by tezos** [comment]
you likely already have a tezos alias, try 
`opam switch remove tezos`

**Comment by Nishkixs** [comment]
`~/Desktop/testnet/tezos (master)$ opam switch remove tezos
Cannot remove tezos as it is the current compiler.`

**Comment by Nishkixs** [comment]
`~/Desktop/testnet/tezos (master)$ opam switch remove tezos`
`Cannot` remove tezos as it is the current compiler.`

**Comment by markrainbow** [comment]
I had the same problem, but solved it creating another switch aliased to version 4.04.1, which changes the current compiler to the new alias, then you can remove tezos using "opam switch remove tezos". Then create the tezos alias again with the version 4.04.2.

**Comment by Nishkixs** [comment]
Hi Mark, 

I'm not sure if the alias isn't switching, or if it could be an issue with the original set up. Any commands I can run to check opam?

`~/Desktop/testnet/tezos (master)$ opam switch tezos --alias-of 4.04.1
~/Desktop/testnet/tezos (master)$ opam switch remove tezos
Cannot remove tezos as it is the current compiler.
`
