### ISSUE TITLE
make failed (Ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by evanrmurphy** [tezos/tezos#72]
Initially my system was showing failures about sodium as reported in #8 when I ran `make build-deps`. [hal9000xp's fix](https://github.com/tezos/tezos/issues/8#issuecomment-319170862) worked to get me through that.

Now when I run `make` I get this failure about `proto/embedded_proto_alpha.cmxa`:

```
evan@evthink:~/src/tezos$ make
make -C src all
make[1]: Entering directory '/home/evan/src/tezos/src'
../tezos-protocol-compiler: symbol lookup error: ../tezos-protocol-compiler: undefined symbol: crypto_pwhash_argon2i_saltbytes
Makefile:368: recipe for target 'proto/embedded_proto_alpha.cmxa' failed
make[1]: *** [proto/embedded_proto_alpha.cmxa] Error 127
make[1]: Leaving directory '/home/evan/src/tezos/src'
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2
evan@evthink:~/src/tezos$ 
```

**Comment by tezos** [comment]
You don't have the correct version of libsodium installed

**Comment by evanrmurphy** [comment]
Thanks for your speedy reply @tezos! I have version 1.0.13 of libsodium, here's the output of your command:

```
evan@evthink:~/src/tezos$ locate libsodium | grep "\.so"
/home/evan/src/libsodium-1.0.13/src/libsodium/.libs/libsodium.so
/home/evan/src/libsodium-1.0.13/src/libsodium/.libs/libsodium.so.18
/home/evan/src/libsodium-1.0.13/src/libsodium/.libs/libsodium.so.18.3.0
/usr/lib/x86_64-linux-gnu/libsodium.so.18
/usr/lib/x86_64-linux-gnu/libsodium.so.18.0.1
/usr/local/lib/libsodium.so
/usr/local/lib/libsodium.so.18
/usr/local/lib/libsodium.so.18.3.0
```

This looks like the most recent version at https://download.libsodium.org/libsodium/releases/ . Which version does tezos require? I checked `src/tezos-deps.opam` and it says `"sodium" {>= "0.3.0" }`.

**Comment by coventry** [comment]
> `/usr/lib/x86_64-linux-gnu/libsodium.so.18.0.1`

You have it, but it looks like you also have another version shadowing it. Which version of the libsodium package do you have?
