### ISSUE TITLE
Distinction between `Variable- vs `Dynamic-length data types should be documented

### ISSUE THREAD

**Issue by coventry** [tezos/tezos#76]
The distinction between [ \``Variable` vs \``Dynamic`](https://github.com/tezos/tezos/blob/master/src/minutils/data_encoding.ml#L72) data-type lengths should be clarified with a comment. I can't tell what the purpose or semantics are, after looking at the next few expressions.

**Comment by coventry** [comment]
Going to have to take a break on tezos for a couple of days, but I think I'm getting the idea, here. Is it that `` `Variable`` entities have a varying but predictable byte-representation length, given the number of elements, whereas the byte lengths of `` `Dynamic` entities can't be predicted until the full byte representation has been parsed?

**Comment by tezos** [comment]
This could use some comments, yes !

For Variable, you are reading the entire buffer passed to `Binary.read`, for Dynamic, the size to be read is included in the buffer, and so it might only be a fraction of it.

For instance, in `Dynamic.(list int)` the binary buffer will start with the list's length, but for `Variable.(list int)`, the length of the list will be size of the buffer divided by the size of an int.

**Comment by coventry** [comment]
Thanks!

**Comment by klakplok** [comment]
Some documentation and tutorial for `Data_encoding` has been merged which explain the difference.
