### ISSUE TITLE
Cannot use default data directory while in sandbox mode

### ISSUE THREAD

**Issue by Nishkixs** [tezos/tezos#80]
`~/Desktop/testnet/tezos (master)$ ./tezos-node run --sandbox --rpc-addr localhost:8732
tezos-node: Error:
              Cannot use default data directory while in sandbox mode`

**Comment by j0sh** [comment]
Looks intentional. Probably to avoid clobbering real data accidentally?

**Comment by OCamlPro-Henry** [comment]
Indeed, this is intentional. But we forgot to update the README... you need to add `--data-dir /tmp/tezos-sandbox`.
