### ISSUE TITLE
toplevel #require'd pkg compilerlibs.optcomp has broken dependency

### ISSUE THREAD

**Issue by coventry** [tezos/tezos#81]
This requirement is generated by `make {node,utils}.top` in `src/.ocamlinit.{node,utils}`. It appears to have a broken dependency, but I can't track down any documentation or source code for it for it.

```
utop # #require "compiler-libs.optcomp";;
Error: Reference to undefined global `Location'
```

**Comment by OCamlPro-Henry** [comment]
It is a bug in `utop` : https://github.com/diml/utop/issues/213

I uploaded a temporary workaround in the tezos repository, thanks for the report.
