### ISSUE TITLE
Doc: timestamp addition

### ISSUE THREAD

**Issue by fab13n** [tezos/tezos#84]
In protocol/alpha/doc/language.md, adding floats to timestamps is mentioned:

    ADD Increment / decrement a timestamp of the given number of seconds.
    :: timestamp : float : 'S -> timestamp : 'S

Since floats are mentioned nowhere else in the doc, I guess it should be `int` instead.

**Comment by coventry** [comment]
[That appears to be the case](https://github.com/tezos/tezos/blob/master/src/proto/alpha/script_interpreter.ml#L224).

**Comment by OCamlPro-Henry** [comment]
The correct rule for adding timestamp and integer is the rule just below the one you cited.

We forgot to remove the rule with `float` when we removed all float operations from the Michelson language. I just uploaded a patch where the rule is removed. Thanks for reporting.
