### ISSUE TITLE
Failure case for Utils.Bounded

### ISSUE THREAD

**Issue by coventry** [tezos/tezos#86]
This came up in testing PR #85. Test below is with the current version of `Bounded`. It ends up with 5 elements, when it should have 6. The cardinality drops on the second insertion of 18, which removes 15 instead of doing nothing.

```ocaml
# module Int = struct type t = int let compare = compare end
module IntBounded = Utils.Bounded(Int)
let ob = IntBounded.create 6;;
<response snipped>

# List.iter (fun x -> IntBounded.insert x ob) [31; 94; 32; 15; 39; 18; ];;
- : unit = ()
# IntBounded.get ob;;
- : int list = [15; 18; 31; 32; 39; 94]
# IntBounded.insert 18 ob;;
- : unit = ()
# IntBounded.get ob;;
- : int list = [18; 31; 32; 39; 94]
#
```

**Comment by OCamlPro-Henry** [comment]
Thanks for spotting this! We don't use this function in context where an element might be insert twice but better to have this function handle it correctly. I just commited a quick fix.
