### ISSUE TITLE
Error: initial amount of contract too low (required 2.00 but provided 2.00)

### ISSUE THREAD

**Issue by tzs1** [tezos/tezos#95]
> ./alphanet.sh client originate contract contract1 for identity transferring 2 from account1 running container:takemymoney.tz 
> Got the source's manager keys (identity).
> Error:
>   Initial amount of contract TZ1n5CCesV9PVj163o6dvP5VBvFhf7SfLjSx too low (required 2.00 but provided 2.00)
> 
> Fatal error: origination simulation failed
> Try `-help` for a list of options and commands.

**Comment by tzs1** [comment]
My question is: where is it stated that the minimum amount is 2.00 for a contract to be originate? And why transferring 2.00 won't work, but instead you need to provide 2.01 to succeed?

**Comment by MiloDavis** [comment]
Fixed as of 67c9e3a.
