### ISSUE TITLE
Base48 encoding?

### ISSUE THREAD

**Issue by tzs1** [tezos/tezos#98]
I think those two are typos (base48 instead of base58):

-  https://github.com/tezos/tezos/blob/6ca9384b890ceba8b694a08c92b73f9201148809/src/utils/base58.mli#L94
- https://github.com/tezos/tezos/blob/59aeb4e7e96222eb6244c0a8207b186ed9891cd1/src/proto/alpha/docs/language.md#L1265

**Comment by OCamlPro-Henry** [comment]
It is not typo, but trace of the Bas48 encoding we were using before switching to the standard Base58. Fixed, thanks for the report.
